### ISSUE TITLE
How to get the red layout?

### ISSUE THREAD

**Issue by elshobokshy** [frankdiox/OnsenUI-YouTube#3]
I couldn't find how did you manage to make the layout red. Could you kindly give me some insight about this matter? Thanks.

**Comment by frandiox** [comment]
@elshobokshy The color is defined in `onsen-css-components.css`. You can generate a new one with custom colors in https://onsen.io/theme-roller/?customize

**Comment by elshobokshy** [comment]
And can't I get the one you used specifically for this project?
